services:
  mlflow:
    container_name: mlflow_server
    build: 
      context: ./mlflow
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=minioaccesskey
      - MINIO_SECRET_KEY=miniosecretkey
    command: ["server", "--console-address", ":9001", "/data"]
    restart: unless-stopped

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_database
    ports:
      - "5432:5432"
    restart: unless-stopped
  fastapi-be:
    build: 
      context: ./back_end
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
  nextjs-fe:
    build:
      context: ./front_end/my-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - fastapi-be